Create a common do_math helper
Leonardo2718/lua-vermelha pull request #10
Opened 2017-01-12 21:04 UTC by charliegracie

Almost 100% of the code for OP_ADD, OP_SUB and OP_MUL is identical. This
means that there are 3 functions with exactly the same code except for
the actual math operation.

This change creates a do_math helper which handles all 3 of the opcodes
above.

Signed-off-by: Charlie Gracie <charlie.gracie@gmail.com>

2017-01-13 14:41 UTC, Leonardo2718 requested changes
Mostly looks good but a few changes are needed.

2017-01-13 14:41 UTC, Leonardo2718 commented on lvjit/LuaFunctionBuilder.cpp
>     auto addints = builder->OrphanBuilder();
Since the operation is not necessarily ADD, I think `addints` should be renamed to something more general like `ints`.

2017-01-13 14:41 UTC, Leonardo2718 commented on lvjit/LuaFunctionBuilder.cpp
>     auto addnums = notints->OrphanBuilder();
Not necessarily doing addition so `addnums` maybe should be `nums`.

2017-01-13 14:41 UTC, Leonardo2718 commented on lvjit/LuaFunctionBuilder.cpp
> +   notnums->     Const(TM_ADD));
Here, cases for `TM_SUB` and `TM_MUL` also need to be handled.

2017-01-13 14:46 UTC, charliegracie commented on lvjit/LuaFunctionBuilder.cpp
>     auto addints = builder->OrphanBuilder();
agreed

2017-01-13 14:46 UTC, charliegracie commented on lvjit/LuaFunctionBuilder.cpp
>     auto addnums = notints->OrphanBuilder();
agreed

2017-01-13 14:47 UTC, charliegracie commented on lvjit/LuaFunctionBuilder.cpp
> +   notnums->     Const(TM_ADD));
Good catch I totally missed that one!  Will push a fix soon

2017-01-16 13:27 UTC, Leonardo2718 approved these changes

2017-01-16 13:27 UTC, merged