Fixes and perf improvements
Leonardo2718/lua-vermelha pull request #17
Opened 2017-01-30 18:19 UTC by charliegracie

1. Fix an issue with OP_CALL where stack grows/moves during the call.  This was easily fixed by reloading base
2. Add support for OP_GETVAL and OP_SETVAL.  Along with adding support I added tests
3. Generate IL for math comparisons in OP_LT, OP_LE, OP_EQ
4. Generate more IL for OP_RETURN
5. Generate more IL for OP_CALL

2017-01-31 13:44 UTC, Leonardo2718 requested changes
Sweet! Great work @charliegracie.

Just a few questions/comments before I merge.

2017-01-31 13:44 UTC, Leonardo2718 commented on lvjit/LuaFunctionBuilder.cpp
> +   TR::IlBuilder *donums = nullptr;
Is there a reason this builder never get's used?

2017-01-31 13:44 UTC, Leonardo2718 commented on lvjit/LuaFunctionBuilder.cpp
> +   auto rightisflt = jit_isfloat(builder, righttype);
Should these be `jit_isfloat(donums, lefttype)`

2017-01-31 13:44 UTC, Leonardo2718 commented on lvjit/LuaFunctionBuilder.cpp
> +   builder->           And(leftisflt, rightisflt));
Should these calls be done on `donums` instead of `builder`?

2017-01-31 13:44 UTC, Leonardo2718 commented on lvjit/LuaFunctionBuilder.cpp
> +   case OP_LT:
Okay. This code works but is a bit confusing. Could you add a brief comment explaining what it's doing?

2017-01-31 13:44 UTC, Leonardo2718 commented on test/opcode/comparisons.lua
> +assert_equal(true, op_le("1","1"), "op_le('1','1')")
With these tests, it might also be worth having non-integral floating point values, e.g. `op_le(1.0,1.1)` and `op_le(1,1.1)`.

2017-01-31 13:44 UTC, Leonardo2718 commented on lvjit/LuaFunctionBuilder.cpp
> +   inlineluaD_precall->		ConvertTo(Int32,
The indenting here doesn't seem quite right.

2017-01-31 13:44 UTC, Leonardo2718 commented on lvjit/LuaFunctionBuilder.cpp
> +   setnils->                ConstInt64(luaTypes.TValue->getSize())));
Could this be simplified by using `IndexAt` instad of `Add`?

2017-01-31 16:47 UTC, charliegracie commented on lvjit/LuaFunctionBuilder.cpp
> +   TR::IlBuilder *donums = nullptr;
yes due to copy and paste error.  It should be used below instead of builder

2017-01-31 16:48 UTC, charliegracie commented on lvjit/LuaFunctionBuilder.cpp
> +   auto rightisflt = jit_isfloat(builder, righttype);
Yes

2017-01-31 16:48 UTC, charliegracie commented on lvjit/LuaFunctionBuilder.cpp
> +   builder->           And(leftisflt, rightisflt));
Correct

2017-01-31 16:48 UTC, charliegracie commented on lvjit/LuaFunctionBuilder.cpp
> +   inlineluaD_precall->		ConvertTo(Int32,
Fixing

2017-01-31 16:48 UTC, charliegracie commented on lvjit/LuaFunctionBuilder.cpp
> +   setnils->                ConstInt64(luaTypes.TValue->getSize())));
Yes that makes more sense.  Copied the code from somewhere else.  In a future change I will fix the location where I copied this code from

2017-01-31 16:48 UTC, charliegracie commented on test/opcode/comparisons.lua
> +assert_equal(true, op_le("1","1"), "op_le('1','1')")
Yes I will add those.

2017-01-31 18:26 UTC, charliegracie commented on lvjit/LuaFunctionBuilder.cpp
> +   case OP_LT:
comments added

2017-02-01 13:56 UTC, Leonardo2718 approved these changes

2017-02-01 14:12 UTC, Leonardo2718 commented
Looks good @charliegracie :smile: 

One question before I merge though: have you done any performance testing for your last two commits (ilgen for OP_CALL and OP_RETURN)? I've been thinking a lot about the implications of these changes. I'm concerned that it may only improve performance on some micro-benchmarks, but actually reduce performance in the general case. The additional ilgen will cause many more nodes to be generated that will likely confuse some JIT optimizations, causing the generated code to run slower.

I'm willing to merge those two commits if you think it will significantly improve performance on benchmarks we care about. Otherwise, I would prefer they be excluded from this PR.

I don't want to lose this work though as I think it could still be very valuable. If we implemented the right inlining heuristics, we could ilgen `luaD_precall` and `luaD_poscall` as _helpers_ and let the inliner figure out whether their worth inlining or not. This would greatly improve our cache locality. 

To this end, you could create a new PR with those two commits as some initial work.

2017-02-01 16:27 UTC, mgaudet commented
I'll just leave [this](https://github.com/eclipse/omr/issues/695) here

2017-02-02 22:16 UTC, charliegracie commented
I will get back to this when I am back from FOSDEM or if I have time while I am there.

2017-02-07 21:08 UTC, charliegracie commented
I have removed the OP_CALL and OP_RETURN implementations for now.  I have them in a separate branch and we can revisit that in the future

2017-02-07 23:17 UTC, merged