Chinese translation of the documentation
Leonardo2718/lua-vermelha pull request #26
Opened 2017-11-08 11:48 UTC by leejingbo

I finished the Chinese translation of the documentaion as I said in issue #25 .

The filename ends with `_zh.md`  .

2017-11-09 15:25 UTC, Leonardo2718 commented
LGTM as far as I can tell.

@xliang6 ?

2017-11-09 16:02 UTC, xliang6 commented
I will review this today.

2017-11-09 21:31 UTC, xliang6 commented on README_zh.md
> +  * [Eclipse Public License](http://www.eclipse.org/legal/epl-v10.html)
FYI, Eclipse OMR is now under the **Eclipse Public License 2.0** and the Apache 2.0 license. The license version recently changed, not a problem with this pull request but a general comment for this lua-vermelha project.

2017-11-09 21:31 UTC, xliang6 commented on doc/zh/building.md
> +当前JIT必须直接链接到VM，所以构建成静态库当前还不被支持。
当前JIT必须直接链接到VM (不管使用什么二进制)，所以构建成共享库当前还不被支持。

2017-11-09 21:31 UTC, xliang6 commented on doc/zh/building.md
> +在构建JIT的时候，如果VM作为C代码来编译就必须定义宏 `LUA_C_LINKAGE` 。这可以保证当把JT和VM链接在一起的时候，不会出现命名粉碎规则(name-mangling)问题。当调用 `make`的时候带上参数 `CXX_FLAGS_EXTRA='-DLUA_C_LINKAGE'` 就定义了 `LUA_C_LINKAGE` 宏（参考根目录下的Makefile）。
这可以保证当把JT和VM链接在一起的时候，不会出现命名混乱问题。

2017-11-09 21:31 UTC, xliang6 commented on doc/zh/building.md
> +| `OMR_COMPILER_ARCH_DIR`    | `$(OMR_COMPILER_DIR)/$(ARCH)`         | Eclipse OMR 编译器CPU特定架构代码 |
Eclipse OMR 编译器特定架构代码目录

2017-11-09 21:31 UTC, xliang6 commented on doc/zh/building.md
> +| `OMR_COMPILER_SUBARCH_DIR` | `$(OMR_COMPILER_ARCH_DIR)/$(SUBARCH)` | Eclipse OMR 编译器CPU特定子架构代码 |
Eclipse OMR 编译器特定子架构代码目录

2017-11-09 23:31 UTC, Leonardo2718 requested changes
@leejingbo, please address @xliang6's comments and then I will merge.

2017-11-09 23:33 UTC, Leonardo2718 commented on README_zh.md
> +  * [Eclipse Public License](http://www.eclipse.org/legal/epl-v10.html)
I'll create a separate issue for this (thanks for reminding me 😛).

2017-11-11 03:03 UTC, xliang6 commented
Looks good to me. One small suggestion: We may want to squash all these commits into one before merging?

2017-11-11 16:28 UTC, Leonardo2718 commented
I don't mind having one commit per "logical unit of translation". So I'm okay with one commit per file. But I don't like having multiple commits for one file. So @leejingbo, would you mind squashing those together?

2017-11-12 00:34 UTC, leejingbo commented
@Leonardo2718 I rebased my repo and squashed the commits. 

@xliang6 Thank you for your suggestion !

2017-11-12 21:04 UTC, Leonardo2718 approved these changes

2017-11-12 21:04 UTC, merged